### ISSUE TITLE
README.md needs updating

### ISSUE THREAD

**Issue by mleduque** [SpellholdStudios/Shadows_over_Soubar#43]
To be in sync with recent changes.

According to the tp2 file :

- Component 4 seems to be "Alternative Soubar area" now
- Component 1 is "Selence arrives to Waukeens Promenade after the meeting with Gaelan in the slums" (and is not number 3)
- Remorhaz walking speed adjustment  is now Component 2

**Comment by Roberciiik** [comment]
Thanks for submitting the issue.
I see what's going on here. The list in the README is just an order of installation prompts, and not designated numbers stored in TP2. I changed the README file to start listing the components from number 1. to not confuse users.

**Comment by mleduque** [comment]
Oh ok, sorry, I misinterpreted the value!
