### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by lukasz-pekala** [SpellholdStudios/Shadows_over_Soubar#9]
I'd like to play this mod in polish so I'm considering starting work on the translation (not sure if I can finish that on my own though - looks like quite a lot of work!).
I also need to find a reviewer once the PR is ready for a review. 

Let's start with a few questions
1. Are you open to contributions?
2. Would you help me by sending announcements "call for reviewers" or "call for translators" on forums?
3. I can see that there is a folder named "Language" contaning strings. There are also ogg files? Are they copied from game resources? How could I find polish ogg resources?

FYI @ALIENQuake  @Gitjas @GwendolyneFreddy @RoxanneSHS @weigo87

**Comment by ALIENQuake** [comment]
@lukasz-pekala Full polish translation is available at Children of Bhaal boards. This mod accepts bug fixes, compatibility fixes, and translation updates from the community. I will now add MAINTENANCE-NOTICE.md

**Comment by GwendolyneFreddy** [comment]
@ALIENQuake Please don't. I am planing to rebuild the README.md file and will add a few more md files, including the maintenance notice.

**Comment by ALIENQuake** [comment]
@GwendolyneFreddy Well, too late 😛 Ok, I'm reverting commit.

**Comment by GwendolyneFreddy** [comment]
Sorry but I am currently reformatting all readme files with the new SHS readme templates, and it takes time. I will update all of them once. So it will be achieved in at least two weeks.

**Comment by ALIENQuake** [comment]
@GwendolyneFreddy Back on this, are you still planning readme modernization for this mod? I believe that MAINTENANCE-NOTICE.md is required for @lukasz-pekala in order to contribute a polish translation.

**Comment by lukasz-pekala** [comment]
> Full polish translation is available at Children of Bhaal boards.

Members of Children of Bhaal boards were not willing to provide their translation last time I asked. I suggest contacting them directly via their boards. I am no longer willing to prepare translation on my own and I don't think doubling the work on translation is a good idea either since a translation exists.

**Comment by Roberciiik** [comment]
Polish translation of this modification is in "alpha" state, as one of the translators said. When ready, it might be added to the 
mod package. Nevertheless, translation can be downloaded from *Children of Bhaal* website, hence closing the issue.
